// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIprjCoreFT.Models
{
    public partial class Camp
    {
        public Camp()
        {
            ActDetail = new HashSet<ActDetail>();
            CampDetail = new HashSet<CampDetail>();
            SetOrderDetail = new HashSet<SetOrderDetail>();
        }

        public int 營區id { get; set; }
        public string 營區名稱 { get; set; }
        public string 營區地址 { get; set; }
        public string 地區 { get; set; }
        public string 縣市 { get; set; }
        public string 營區介紹 { get; set; }
        public int? 容納人數 { get; set; }
        public string 建立人 { get; set; }
        public DateTime? 建立時間 { get; set; }
        public string 修改人 { get; set; }
        public DateTime? 修改時間 { get; set; }

        public virtual ICollection<ActDetail> ActDetail { get; set; }
        public virtual ICollection<CampDetail> CampDetail { get; set; }
        public virtual ICollection<SetOrderDetail> SetOrderDetail { get; set; }
    }
}